### ISSUE TITLE
Some SerifEthiopic letters are too similar

### ISSUE THREAD

**Issue by marekjez86** [notofonts/ethiopic#5]
the difference between ሰ and ስ is too subtle 

![SerifEthiopic-95FQhSB3LzFNtd7](https://user-images.githubusercontent.com/13322623/158686782-a7ba3a5d-224f-4507-b8bf-694bd7434a40.png)

At a quick glance they look almost the same to me (the first letter (ሰ) has a slight tilt, maybe it is the serif?  and the second letter (ስ) doesn't have much larger of a tilt that the first letter).

Compare this to wikipedia's Amharic page where the difference between the two is more noticeable: 
![SerifEthiopic-5K2ey24HyDVgcHu](https://user-images.githubusercontent.com/13322623/158686880-dcd3e262-3376-451e-a494-95876b1bcf5c.png)

For ሸ and ሽ 
![SerifEthiopic-5aJmDmw3vg5GTUP](https://user-images.githubusercontent.com/13322623/158687019-761e6638-d90b-4b57-bd0d-e8635366ab6b.png)

because the horizontal line is close to the upside-down u, it may be hard to tell if the line between them is vertical or slanted

**Comment by Mercury13** [comment]
Wikipedia does not have its own font, and even shows where to get one. Because of very high resolution and Helvetica-like standard font, I suspect that topic-starter has Mac. And topic-starter’s font is really nice: does not repeat Ge’ez calligraphy like SIL’s one, but very sloppy, unlike straight and sleek Noto.

**Comment by Mercury13** [comment]
I decided to investigate others’ fonts. Most fonts (e.g. SIL Abyssinica) mimic thick pen calligraphy — so be it… Your Serif and Mac’s what’s-its-name are somewhat unique — they are modern yet modulated.
![image](https://user-images.githubusercontent.com/10164882/200101811-f25e3802-9eae-4afd-b7d6-0f06344ed246.png)
Nothing special, just smaller serifs. Probably greater slant and/or smaller serif is what you should do specifically on SE for SA/SE distinguishability.

![image](https://user-images.githubusercontent.com/10164882/200101883-8063f717-7907-4ad2-8ddc-e489a8f0f173.png)
SIL has several bones :), that’s not your case, you’ve got sleek Serif, rather than simulate calligraphy with a thick pen. But in SHE the bone is also shifted to the left very much. And no traces of serif in slanted stroke. And even greater slant than on SA.

These are your SHA/SHE.
![image](https://user-images.githubusercontent.com/10164882/200102021-960f0b24-5578-4fd0-9146-da507f6cb2f9.png)
Slant is 62 units, the bone is shifted just 31 units left. And traces of serif.

**Comment by Mercury13** [comment]
That’s how they look in my Unicodia — really indistiguishable.
![image](https://user-images.githubusercontent.com/10164882/200102235-77a199bd-9d12-442d-9ba3-6953613aabf6.png)

**Comment by Mercury13** [comment]
Mac’s approach is unique: they decided to totally scrap that serif of SE. Not really historic (try to write that letter with a low-quality pen), but helps in legibility.

**Comment by Mercury13** [comment]
+1 Noto vs Abyssinica: in Abyssinica’s SHE the stroke grows from a different place.
And I decided to compare SE vs SHE.
![image](https://user-images.githubusercontent.com/10164882/200102897-2ec76433-9f6e-4858-87d2-e88bd920a0c4.png)
![image](https://user-images.githubusercontent.com/10164882/200103142-2263ae58-5bf5-4abb-adbf-f40612e7ad13.png)
Abyssinica’s SHE is ju-ust a bit smaller to accentuate this stroke. Just SHE: e.g. SHI and SHO are of normal size.

**Comment by Mercury13** [comment]
It seems to me, the approach should be complex.
1. Make the slanted stroke of SE/SHE grow from the other place, especially in SE.
2. Make the serif smaller in SE, and almost completely dispose of in SHE (leave just a small rounding).
3. Make main letter of SHE a bit smaller to accentuate slanted stroke.
4. Move the bone of SHE greatly to the left. (And rekern, of course.)

**Comment by Mercury13** [comment]
I can try, but I work in Inkscape/FontForge, the font will be totally broken after my work (tested). So you”ll need to convert my work to your sources.

**Comment by simoncozens** [comment]
Just to get a second opinion on this, @dyacob, what do you think about our sa/se - sha/she glyphs?

![shape](https://github.com/notofonts/ethiopic/assets/106728/02144f21-c644-4cdf-84c3-10dcc4302dbe)

Is there a problem here and if so what's the best approach to fix?

**Comment by dyacob** [comment]
Hi @simoncozens , I saw this ticket earlier and debated how best to provide input.  At small point sizes, the distinctions between these forms (1st and 6th orders) can be subtle and difficult to discern with some typefaces; then exaggerating the slant is helpful.  Honestly though, I haven't experienced any sense of ambiguity reading Noto Ethiopic as provided on my Android phones at the default size settings (Samsung S9, then later S22). 

The central position of the top stroke seems fine.  The rightward serif at the top of ስ (U+1235) I don't at all notice on my phone, the stroke looks great, like a gentle curve.  On my MacBook at regular font sizes, it _does_ look odd. Initially like there is a "knob" on top of a stroke, then at larger sizes it becomes a "handle".  

So it stops being something subtle like a serif, and becomes more of a glyph component.  Looking at @simoncozens screenshot, the top stroke serif appears to match the serifs at the bottoms of the legs -it should definitely be less, like half as much, I think matching and mirroring the extent that we see on the top s stroke of ሰ (U+1230).

This rightward gesture is more subtle in Abyssinica, Nyala could definitely tone it back a bit in this respect also. Instinctively, I think the top stroke serif should flow to the left, just thinking about the handwritten motion.  The slight hooking to the right may have some optical benefit to clarity at small sizes (where I don't notice it).

**Comment by simoncozens** [comment]
Thank you so much for the detailed reply. The relevant part for me is that you haven't found any ambiguity in reading; it feels like we may be able to tidy it up a little more but it's not currently causing any readability problems. So I shall close this for nwo.

**Comment by Mercury13** [comment]
Android has high enough resolution, 1× Windows does not. Need exaggeration.

**Comment by simoncozens** [comment]
Let's fix the hinting. :-)

**Comment by Mercury13** [comment]
Hinting is not an issue, it’s seemingly OK and hinting rarely catches slanted lines. On SHE move bone AMAP to the left, and totally get rid of traces of serif. On SE reduce serif, maybe increase slant, and move that thing to the left.

As you see, unhinted OTF kinda improved SHE and did nothing with SE.
![image](https://github.com/user-attachments/assets/355b87f5-c9a2-4984-b956-a969cbcf28c3)

Same unhinted OTF, but craggy hand-editing.
![image](https://github.com/user-attachments/assets/c5d9225c-1c8a-41f4-ae0b-cadc3328713f)

And I see why unhinted SHE is better. Unhinted font just gave it ½ vertical pixel more, 2.5 instead of 2. For SE there was no horizontal/vertical thing to hint to, so 3.5 and 3.5.

**Comment by Mercury13** [comment]
So another recipe working for SHE only: make main letter a bit smaller. IMHO it might be an overkill, I’m in favour of deleting/reducing traces of serif. Even w/o moving the bone it should improve things.
